### PR TITLE
First release

### PR DESCRIPTION
**Pull request by ljlamarche**
This PR will be the first release of MIVIT.  I'm trying to get this out for CEDAR, so unless anyone sees anything glaring (I don't expect any of you to do a full code review), I'm going to merge this tomorrow morning.  We can deal with bugs and other issues as they come up, but I want to have at least something out before the python session for people to play with.

### CODE REVIEW

**Comment by asreimer** [comment]
I'll look in the morning!

**Comment by asreimer** [comment]
This looks good.  I didn't see any obvious problems in the code.

I did try running the test_mivit.py code and it wasn't able to find any Mango data:

    [asreimer@thomson MIVIT]$ python test_mivit.py 
    Attempting to download HMay2817.h5 from FTP server.
    Exception: No data available for Hat Creek Observatory on 2017-05-28.
    Attempting to download CMay2817.h5 from FTP server.
    Exception: No data available for Capitol Reef Field Station on 2017-05-28.
    Attempting to download BMay2817.h5 from FTP server.
    Exception: No data available for Bridger on 2017-05-28.
    Attempting to download IMay2817.h5 from FTP server.
    Exception: No data available for Eastern Iowa Observatory on 2017-05-28.
    Attempting to download LMay2817.h5 from FTP server.
    Exception: No data available for Millstone Hill Observatory on 2017-05-28.
    Attempting to download PMay2817.h5 from FTP server.
    Exception: No data available for Pisgah Astronomical Observatory on 2017-05-28.
    Attempting to download RMay2817.h5 from FTP server.
    Exception: No data available for Rainwater Observatory on 2017-05-28.
    Attempting to download MMay2817.h5 from FTP server.
    Exception: No data available for Madison on 2017-05-28.
    Attempting to download DMay2817.h5 from FTP server.
    Exception: No data available for McDonald Observatory on 2017-05-28.
    Traceback (most recent call last):
      File "test_mivit.py", line 153, in <module>
        main()
      File "test_mivit.py", line 147, in main
        test()
      File "test_mivit.py", line 31, in test
        mango_data = mivit.helper.mango.mosaic(targtime,mangopy_kwargs=mangopy_kwargs)
      File "/home/asreimer/projects/ingeo/src/MIVIT/mivit/helper/mango.py", line 26, in     mosaic
        time_range = [min(time), max(time)+dt.timedelta(minutes=5)]
    ValueError: min() arg is an empty sequence

Is it intended for the test_mivit.py supposed to work or was this just for development purposes?

**Comment by ljlamarche** [comment]
Thanks, and yeah, I'm not surprised test_mivit.py didn't work - it's a file path issue.  I'm putting together a tutorial notebook now that should be a little more durable.  The problem is really data access.  We still can't fetch SuperDARN data and the MANGO data for the really interesting Memorial Day Storm isn't on the FTP site.  Both those data are in the MemorialDayStorm data set that we put together for Resen, so I'm going to design the tutorial to use those data, but I'm still not sure how we should make that data set available to people who want to try out the software.  All I can think to do easily zip the directory and add it to the git repo.  Got any ideas for that?  It IS hard to demo data visualization software without data access... :(

**Comment by asreimer** [comment]
I think it is appropriate to link to https://ingeo.datatransport.org/data/datasets/MemorialDayStorm/ for the MIVIT tutorial (MIVIT is an ingeo product). You could place a zip there and instruct people to download it and extract the zip in the same directory as the tutorial file. Then use relative paths in the tutorial.

**Comment by ljlamarche** [comment]
Excellent, I'll do that!  Thanks!

**Pull request merged**
